export class ActionsEnums {
  static TODO = {
    GET_TODOS: 'GET_TODOS',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_ERROR: 'GET_TODOS_ERROR',
    ADD_TODO: 'ADD_TODO',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_ERROR: 'ADD_TODO_ERROR',
    TOGGLE_DONE: 'TOGGLE_DONE',
    TOGGLE_DONE_SUCCESS: 'TOGGLE_DONE_SUCCESS',
    TOGGLE_DONE_ERROR: 'TOGGLE_DONE_ERROR',
  }

  // static VISIBILITY_FILTER = {
    static SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
  // }
}
